# Generated by Django 4.0.5 on 2022-06-01 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('secret_identity', models.CharField(max_length=100)),
                ('img', models.CharField(max_length=500)),
                ('bio', models.TextField(max_length=500)),
                ('powers', models.CharField(max_length=200)),
                ('universe', models.CharField(max_length=50)),
                ('affiliations', models.TextField(max_length=500)),
                ('villains', models.TextField(max_length=500)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Villain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('img', models.CharField(max_length=500)),
                ('bio', models.TextField(max_length=500)),
                ('powers', models.CharField(max_length=200)),
                ('universe', models.CharField(max_length=50)),
                ('affiliations', models.TextField(max_length=500)),
                ('nemesis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hero', to='main_app.hero')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VillainTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.CharField(default='https://cdn.europosters.eu/image/1300/posters/dc-comics-rebirth-i80856.jpg', max_length=500)),
                ('villains', models.ManyToManyField(to='main_app.villain')),
            ],
        ),
        migrations.CreateModel(
            name='HeroTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.CharField(default='https://cdn.europosters.eu/image/1300/posters/dc-comics-rebirth-i80856.jpg', max_length=500)),
                ('heroes', models.ManyToManyField(to='main_app.hero')),
            ],
        ),
    ]
