# Generated by Django 4.0.5 on 2022-06-01 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hero',
            old_name='powers',
            new_name='abilties',
        ),
        migrations.RenameField(
            model_name='villain',
            old_name='powers',
            new_name='abilities',
        ),
        migrations.RemoveField(
            model_name='hero',
            name='universe',
        ),
        migrations.RemoveField(
            model_name='villain',
            name='universe',
        ),
    ]
