# Generated by Django 4.0.4 on 2022-05-31 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Villain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('img', models.CharField(max_length=500)),
                ('bio', models.TextField(max_length=500)),
                ('powers', models.CharField(max_length=200)),
                ('universe', models.CharField(max_length=50)),
                ('affiliations', models.TextField(max_length=500)),
                ('nemesis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='villains', to='main_app.hero')),
            ],
        ),
    ]
