# Generated by Django 4.0.5 on 2022-06-01 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_powers_hero_abilties_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hero',
            old_name='abilties',
            new_name='abilities',
        ),
    ]
